config/routes.rb
Kabupatenku::Application.routes.draw do

  mount Tolk::Engine => '/tolk', :as => 'tolk'

  devise_for :users

  resources :registrations, :only => [:show]

  resources :users, :only => [:index, :show, :edit, :update]
  resources :provinces

  resources :kabupatens do
    get :autocomplete_kabupaten_name, :on => :collection
    resources :links,    :only => [:create, :update, :destroy]
  end

  resources :projects do
    resources :links,    :only => [:create, :update, :destroy]
  end
  resources :contacts
  resources :sectors

  resource :dashboard, :controller => "dashboard", :only => [:show]
  resource :corporate, :controller => "corporate", :only => [:show]
  resource :translate, :controller => "translate", :only => [] do
    member do
      post 'translate'
    end
  end

  resource :admins

  resources :snippets

  authenticated :user do
    root :to => 'dashboard#show'
  end

  root :to => "dashboard#show"

end

app/models/user.rb
class User < ActiveRecord::Base
	rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :projects

  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false

  before_save :setup_role, :if => lambda { |u| u.new_record? }

  def role_names
    roles.map(&:name).uniq.sort
  end

  private

  # Setup default role
  def setup_role
    self.add_role('contributor') unless self.roles.present?
  end


end

app/controllers/users_controller.rb
class UsersController < AdminsController

  load_and_authorize_resource
  before_filter :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name).all.paginate(page: params[:page], per_page: 15)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    # HABTM associations
    # Overwrite existing roles. If params[:roles] is nil then remove all roles.
    @user.remove_role Role::ROLES
    params[:roles].each { |role| @user.add_role(role) }

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
%h2{style: 'margin-bottom: 10px'} Edit #{@user.name}

= form_for(@user, :html => { :class => 'form-horizontal', :method => :put }) do |f|
  / = devise_error_messages!
  .field.control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .field.control-group
    = f.label :email, :class => 'control-label'
    .controls
      = f.email_field :email, :class => 'email_field'
  .field.control-group
    = f.label :roles, :class => 'control-label'
    .controls
      - Role::ROLES.sort.each do |role|
        %label.checkbox
          = check_box_tag("roles[]", role, @user.has_role?(role))
          = role
  .field.control-group
    = f.label :password, :class => 'control-label'
    .controls
      = f.password_field :password, :autocomplete => "off", :class => 'password_field'
      %i (leave blank if you don't want to change it)
  .field.control-group
    = f.label :password_confirmation, :class => 'control-label'
    .controls
      = f.password_field :password_confirmation, :class => 'password_field'
  %div= f.submit "Update", :class => 'btn btn-primary'
/ %h3 Cancel my account
/ %p
/   Unhappy? #{link_to "Cancel my account", registration_path(@resource_name), :data => { :confirm => "Are you sure?" }, :method => :delete}.
= link_to "Back", user_path(@user), :class => 'btn'

app/views/users/index.html.haml
- @page_title = 'Users'

- if @users.present?

  %p= page_entries_info @users

  %table.table.table-striped
    %tr
      %th Name
      %th Email
      %th Roles
      %th
      %th
      %th

    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.email
        %td= user.role_names.join(', ')
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete

  = will_paginate @users

-else
  %p There are no users to list

%br

/ = link_to 'New user', new_user_path

app/views/users/show.html.haml
- @page_title = @user.name
- @body_class = "users"

/ %p#notice= notice

%table.simple_table
  %tr
    %th Name:
    %td= @user.name
  %tr
    %th Email:
    %td= @user.email
  %tr
    %th Current Sign In:
    %td= @user.current_sign_in_at.try(:to_formatted_s, :short_dmy_with_time)
  %tr
    %th Current Sign In IP:
    %td= @user.current_sign_in_ip
  %tr
    %th Last Sign In:
    %td= @user.last_sign_in_at.try(:to_formatted_s, :short_dmy_with_time)
  %tr
    %th Last Sign In IP:
    %td= @user.last_sign_in_ip
  %tr
    %th Roles:
    %td
      - @user.role_names.each do |role|
        %span= role
        %br

- if can? :update, @user
  = link_to 'Edit', edit_user_path(@user), :class => 'btn'
= link_to 'Back', users_path, :class => 'btn'