config/routes.rb
Kabupatenku::Application.routes.draw do

  mount Tolk::Engine => '/tolk', :as => 'tolk'

  devise_for :users

  resources :registrations, :only => [:show]

  resources :users, :only => [:index, :show, :edit, :update]
  resources :provinces

  resources :kabupatens do
    get :autocomplete_kabupaten_name, :on => :collection
    resources :links,    :only => [:create, :update, :destroy]
  end

  resources :projects do
    resources :links,    :only => [:create, :update, :destroy]
  end
  resources :contacts
  resources :sectors

  resource :dashboard, :controller => "dashboard", :only => [:show]
  resource :corporate, :controller => "corporate", :only => [:show]
  resource :translate, :controller => "translate", :only => [] do
    member do
      post 'translate'
    end
  end

  resource :admins

  resources :snippets

  authenticated :user do
    root :to => 'dashboard#show'
  end

  root :to => "dashboard#show"

end

app/models/kabupaten.rb
class Kabupaten < ActiveRecord::Base
  translates :description, :fallbacks_for_empty_translations => true
  include Locale
  store :health_indicators, accessors: [:female_life_expectancy, :male_life_expectancy]

  belongs_to  :province
  belongs_to  :category, :class_name => 'Dt2Category'
  has_many    :project_kabupaten_mappings
  has_many    :projects, :through => :project_kabupaten_mappings
  has_many    :links, :as => :linkable, :dependent => :destroy

  scope :in_province, lambda { |province| where("province_id = ?", province) }

  validates_uniqueness_of :name

  before_save :strip_empty_html_translation_fields

  def category_name
    category.name + ' ' + name
  end

  def density
    (population / area.to_f).ceil if area.present?
  end


  private

  def strip_empty_html_translation_fields
    # http://stackoverflow.com/questions/7414267/strip-html-from-string-ruby-on-rails
    self.description = nil if description.blank? || ActionView::Base.full_sanitizer.sanitize(description).strip.blank?
  end

end

app/controllers/kabupatens_controller.rb
class KabupatensController < ApplicationController

  before_filter :authenticate_user!, :except => [:index, :show, :autocomplete_kabupaten_name]
  before_filter :globalize_fallbacks
  load_and_authorize_resource :except => [:autocomplete_kabupaten_name]

  autocomplete :kabupaten, :name, full: true, limit: 15


  # GET /kabupatens
  # GET /kabupatens.json
  def index
    if params[:province]
      @province = Province.find(params[:province])
      @kabupatens = Kabupaten.in_province(params[:province]).order('kabupatens.name asc').paginate(page: params[:page], per_page: 15)
    else
      @kabupatens = Kabupaten.includes(:province).order('provinces.name asc, kabupatens.name asc').paginate(page: params[:page], per_page: 15)
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kabupatens }
    end
  end

  # GET /kabupatens/1
  # GET /kabupatens/1.json
  # GET /kabupatens/0?&kabupaten_name=Aceh+Barat
  def show
    if params[:name]
      @kabupaten = Kabupaten.where(id: params[:id_for_name]).first || Kabupaten.where(name: params[:name]).first
      unless @kabupaten
        flash[:error] = "No Kabupaten/Kota with name #{params[:name]}"
        redirect_to :back
        return
      end
    else
      @kabupaten = Kabupaten.find(params[:id])
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @kabupaten }
    end
  end

  # GET /kabupatens/new
  # GET /kabupatens/new.json
  def new
    @kabupaten = Kabupaten.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @kabupaten }
    end
  end

  # GET /kabupatens/1/edit
  def edit
    @kabupaten = Kabupaten.find(params[:id])
  end

  # POST /kabupatens
  # POST /kabupatens.json
  def create
    @kabupaten = Kabupaten.new(params[:kabupaten])

    respond_to do |format|
      if @kabupaten.save
        format.html { redirect_to @kabupaten, notice: 'Kabupaten was successfully created.' }
        format.json { render json: @kabupaten, status: :created, location: @kabupaten }
      else
        format.html { render action: "new" }
        format.json { render json: @kabupaten.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /kabupatens/1
  # PUT /kabupatens/1.json
  def update
    @kabupaten = Kabupaten.find(params[:id])

    respond_to do |format|
      if @kabupaten.update_attributes(params[:kabupaten])
        format.html { redirect_to @kabupaten, notice: 'Kabupaten was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @kabupaten.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kabupatens/1
  # DELETE /kabupatens/1.json
  def destroy
    @kabupaten = kabupaten.find(params[:id])
    @kabupaten.destroy

    respond_to do |format|
      format.html { redirect_to kabupatens_url }
      format.json { head :ok }
    end
  end

end

app/helpers/kabupatens_helper.rb
module KabupatensHelper

  def number_with_delimiter(number, delimiter=",")
    number.to_s.gsub(/(\d)(?=(\d\d\d)+(?!\d))/, "\\1#{delimiter}")
  end
  
end

app/views/kabupatens/_form.html.haml
:plain
  <script type="text/javascript">
         bkLib.onDomLoaded(function() { nicEditors.allTextAreas() });
  </script>

= form_for @kabupaten, :html => { :class => 'form-horizontal' } do |f|
  -if @kabupaten.errors.any?
    #error_explanation
      %h2= "#{pluralize(@kabupaten.errors.count, "error")} prohibited this kabupaten from being saved:"
      %ul
        - @kabupaten.errors.full_messages.each do |msg|
          %li= msg

  .field.control-group
    = f.label t('kabupaten.kabupaten_name'), :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .field.control-group
    = f.label t('kabupaten.category'), :class => 'control-label'
    .controls
      = f.collection_select :category_id, Dt2Category.all(:order=>:name), :id, :name, {:value => "Kabupaten"}
  .field.control-group
    = f.label t('kabupaten.description'), :class => 'control-label'
    .controls
      = f.text_area :description, :value => raw(f.object.send(:locale_attr_or_alt_translation, :description)), :rows => 5, :class => 'text_area', :style => 'width: 500px'
  .field.control-group
    = f.label t('kabupaten.area'), :class => 'control-label'
    .controls
      = f.number_field :area, :class => 'number_field'
      = raw("(km<sup>2</sup>)")
  .field.control-group
    = f.label t('kabupaten.population'), :class => 'control-label'
    .controls
      = f.number_field :population, :class => 'number_field'
  .field.control-group
    = f.label t('kabupaten.capital'), :class => 'control-label'
    .controls
      = f.text_field :capital, :class => 'text_field'
  .field.control-group
    = f.label t('kabupaten.province'), :class => 'control-label'
    .controls
      = f.collection_select :province_id, Province.all(:order=>:name), :id, :name, {:include_blank => true}
  .actions.form-actions
    = f.submit 'Save', :class => 'btn btn-primary'

app/views/kabupatens/edit.html.haml
- @page_title = "Editing kabupaten"
- @body_class = "kabupatens"

= render 'form'

= link_to 'Show', @kabupaten, :class => 'btn'
= link_to 'Back', kabupatens_path, :class => 'btn'
- if can? :manage, Kabupaten
  = link_to 'Destroy', @kabupaten, :class => 'btn btn-danger', :confirm => 'Are you sure?', :method => :delete

app/views/kabupatens/index.html.haml
- content_for :javascript_includes do
  = javascript_include_tag 'kabupatens'

- if @province
  - @page_title = "#{t('kabupaten.kabupaten_list')} #{t('general.in')} #{@province.name}"
- else
  - @page_title = t('kabupaten.kabupaten_list')
- @body_class = "kabupatens"

- if @kabupatens.present?

  = form_tag kabupaten_path(1), method: :get do
    = hidden_field_tag :id_for_name
    %input{:type => 'submit', :value => t('kabupaten.buttons.show_kabupaten'), class: 'enable_on_input btn', style: 'vertical-align: top', disabled: true}
    = autocomplete_field_tag :name, '', autocomplete_kabupaten_name_kabupatens_path, class: 'enable_submit', id_element: "#id_for_name"


  %p= page_entries_info @kabupatens

  %table.table.table-striped
    %tr
      %th= t('kabupaten.province')
      %th= t('kabupaten.kabupaten_name')
      %th.right
        = t('kabupaten.area')
        = raw("(km<sup>2</sup>)")
      %th.right= t('kabupaten.population')
      %th.right= t('kabupaten.density')

    - @kabupatens.each do |kabupaten|
      %tr
        %td= link_to kabupaten.province.name, kabupaten.province
        %td= link_to kabupaten.category_name, kabupaten
        %td.right= number_with_delimiter(kabupaten.area)
        %td.right= number_with_delimiter(kabupaten.population)
        %td.right= number_with_delimiter(kabupaten.density)

  = will_paginate @kabupatens

-else
  %p There are no kabupatens to list
%br

- if can? :manage, Kabupaten
  = link_to 'Add New', new_kabupaten_path, :class => 'btn btn-primary'

app/views/kabupatens/new.html.haml
%h1 New kabupaten

= render 'form'

= link_to 'Back', kabupatens_path, :class => 'btn'

app/views/kabupatens/show.html.haml
%style
  :sass
    div
      .actions
        margin-bottom: 20px

- @page_title = @kabupaten.category_name
- @body_class = "kabupatens"

/ %p#notice= notice

#kabupaten_description
  = raw(@kabupaten.description || "&nbsp;")
  - if Translate.for_translation?(@kabupaten, 'description')
    .alert{style: 'margin-top: 10px'}
      = t('kabupaten.translate_alert')
      %br
      - translate_button('kabupaten_description')

= render :partial => '/links', :locals => {:linkable => @kabupaten}

- content_for :sidebar do
  .actions
    = link_to t('kabupaten.project_list'), projects_path(filter: { :kabupaten_id => @kabupaten.id })
  %p
    %b= raw("#{t('kabupaten.area')} (km<sup>2</sup>):")
    = number_with_delimiter(@kabupaten.area)
  %p
    %b= "#{t('kabupaten.population')}:"
    = number_with_delimiter(@kabupaten.population)
  %p
    %b= "#{t('kabupaten.capital')}:"
    = @kabupaten.capital
  %p
    %b= "#{t('kabupaten.province')}:"
    = @kabupaten.province.name

- content_for :bottom do
  - if can? :update, @kabupaten
    = link_to 'Edit', edit_kabupaten_path(@kabupaten), :class => 'btn'
  = link_to 'Back', kabupatens_path, :class => 'btn'