config/routes.rb
Kabupatenku::Application.routes.draw do

  mount Tolk::Engine => '/tolk', :as => 'tolk'

  devise_for :users

  resources :registrations, :only => [:show]

  resources :users, :only => [:index, :show, :edit, :update]
  resources :provinces

  resources :kabupatens do
    get :autocomplete_kabupaten_name, :on => :collection
    resources :links,    :only => [:create, :update, :destroy]
  end

  resources :projects do
    resources :links,    :only => [:create, :update, :destroy]
  end
  resources :contacts
  resources :sectors

  resource :dashboard, :controller => "dashboard", :only => [:show]
  resource :corporate, :controller => "corporate", :only => [:show]
  resource :translate, :controller => "translate", :only => [] do
    member do
      post 'translate'
    end
  end

  resource :admins

  resources :snippets

  authenticated :user do
    root :to => 'dashboard#show'
  end

  root :to => "dashboard#show"

end

app/models/project.rb
class Project < ActiveRecord::Base
  translates :name, :description, :fallbacks_for_empty_translations => true
  include Locale

  self.table_name = 'projects'

  attr_accessible :description, :name, :project_kabupaten_mappings_attributes

  belongs_to :user

  has_many :project_kabupaten_mappings
  has_many :kabupatens, :through => :project_kabupaten_mappings
  has_many :project_contact_mappings
  has_many :contacts, :through => :project_contact_mappings
  has_many :project_sector_mappings
  has_many :sectors, :through => :project_sector_mappings
  has_many :links, :as => :linkable, :dependent => :destroy

  scope :in_kabupaten, lambda { |kabupaten| includes(:kabupatens).where("kabupatens.id = ?", kabupaten) }
  scope :in_sector, lambda { |sectors| includes(:sectors).where("sectors.id IN (?)", sectors) }
  scope :search, lambda { |term|
    term = '%' + term.to_s.downcase + '%'
    where( "LOWER(name) LIKE ? OR LOWER(description) LIKE ?", term, term).limit(100)
  }

  accepts_nested_attributes_for :project_kabupaten_mappings, :reject_if => :all_blank, :allow_destroy => true

  before_save :strip_empty_html_translation_fields

  class << self

    # In location AND contains search terms AND in sectors
    def filter(conditions)
      result = []
      result += in_kabupaten(conditions[:kabupaten_id]) if conditions[:kabupaten_id].present?
      if conditions[:search].present?
        result = result.present? ? result & search(conditions[:search]) : search(conditions[:search])
      end
      sectors = conditions[:sector_id].present? ? conditions[:sector_id].reject{|s| s.empty?} : []
      if sectors.present?
        result = result.present? ? result & in_sector(sectors) : in_sector(sectors)
      end
      result.uniq
    end

  end

  private

  def strip_empty_html_translation_fields
    # http://stackoverflow.com/questions/7414267/strip-html-from-string-ruby-on-rails
    self.description = nil if ActionView::Base.full_sanitizer.sanitize(description).blank?
  end

end

app/controllers/projects_controller.rb
require 'will_paginate/array'

class ProjectsController < ApplicationController

  load_and_authorize_resource

  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :globalize_fallbacks

  # GET /projects
  # GET /projects.json
  def index
    if params[:filter] && params[:filter].any? {|k,v| v.is_a?(Array) ? v.any?{|a| !a.blank?} : !v.blank?}
      filter = params[:filter]
      @kabupaten = Kabupaten.find(filter[:kabupaten_id]) if filter[:kabupaten_id].present?
      projects = Project.filter(filter)
    else
      params.delete(:filter)
      projects = Project.limit(100)
    end
    # Sort by name for the current locale, so need to use sort_by because cannot use :order.
    @projects = projects.sort_by{|p| p.name.to_s.downcase}.paginate(page: params[:page], per_page: 15)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])
    @project.user = current_user

    # HABTM associations
    @project.sectors = Sector.find_all_by_id(params[:sector_ids])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    # HABTM associations
    # Overwrite existing sectors. If params[:sector_ids] is nil then remove all areas.
    @project.sectors = Sector.find_all_by_id(params[:sector_ids])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
:plain
  <script type="text/javascript">
         bkLib.onDomLoaded(function() { nicEditors.allTextAreas() });
  </script>

= form_for @project, :html => { :class => 'form-horizontal' } do |f|
  -if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  .field.control-group
    = f.label t('kabupaten.title'), :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .field.control-group
    = f.label t('kabupaten.description'), :class => 'control-label'
    .controls
      = f.text_area :description, :value => raw(f.object.send(:locale_attr_or_alt_translation, :description)), :rows => 5, :class => 'text_area', :style => 'width: 500px'
  .field.control-group
    = f.label t('kabupaten.location').titleize, :class => 'control-label'
    .controls

      #kabupatens
        %table.simple_list
          %thead
            %tr
              %th{ :colspan => 3 } &nbsp;
              %th
                = link_to_add_association f, :project_kabupaten_mappings, { 'data-association-insertion-node' => '#kabupatens .nested-fields:last', 'data-association-insertion-position' => 'after' } do
                  - add_button
          %tbody
            = f.fields_for :project_kabupaten_mappings do |ff|
              = render :partial => 'project_kabupaten_mapping_fields', :locals => { :f => ff }

  .field.control-group
    = f.label t('kabupaten.sector').titleize, :class => 'control-label'
    .controls
      - Sector.by_name.each do |sector|
        %label.checkbox
          = check_box_tag("sector_ids[]", sector.id, @project.sectors.include?(sector), :id => "sector_#{sector.id}")
          = sector.name


  .actions.form-actions
    = f.submit 'Save', :class => 'btn btn-primary'

app/views/projects/_project_kabupaten_mapping_fields.html.haml
%tr.nested-fields
  - if f.object.new_record?
    %td{ :colspan => 2 }
      = f.grouped_collection_select :kabupaten_id, Province.by_name, :kabupatens, :name, :id, :category_name, {:prompt => '--- Select Kabupaten ---'}
  - else
    %td
      %strong= "#{f.object.kabupaten.province.name}: "
    %td{ :title => f.object.kabupaten.name }
      = truncate(f.object.kabupaten.category_name, :length => 75)
  %td
    = link_to_remove_association f do
      - remove_button

app/views/projects/edit.html.haml
- @page_title = "Editing project"
- @body_class = "projects"

= render 'form'

= link_to 'Show', @project, :class => 'btn'
= link_to 'Back', projects_path, :class => 'btn'
- if can? :manage, Project
  = link_to 'Destroy', @project, :class => 'btn btn-danger', :data => {:confirm => 'Are you sure?'}, :method => :delete

app/views/projects/index.html.haml
- content_for :javascript_includes do
  = javascript_include_tag 'kabupatens'

%style
  :sass
    #filter_options
      table
        td
          padding: 10px
      .ui-multiselect
        margin-bottom: 10px
        min-height: 28px
    .ui-multiselect-checkboxes
      label
        margin-bottom: 0px
        input
          display: inline-block
          margin-right: 5px
          margin-bottom: 5px
          vertical-align: top
        span
          vertical-align: bottom

- if @kabupaten
  - @page_title = "#{t('kabupaten.project_list')} #{t('general.in')} #{@kabupaten.category_name}"
- else
  - @page_title = t('kabupaten.project_list')

- @body_class = "projects"

#filter
  - if params[:filter]
    %p= "Filtered for: "
  = form_tag projects_path, method: :get do

    #filter_options
      %table
        %thead
          %tr
            %th= t('kabupaten.sector').titleize
            %th= t('kabupaten.contains')
            %th= t('kabupaten.location').titleize
            %th
        %tbody
          %tr
            %td
              = select_tag :sector_id, options_for_select(Sector.all(:order=>:name).map{|s| [s.name, s.id]}, params[:filter] ? params[:filter][:sector_id] : nil), :name => "filter[sector_id][]", :multiple => true, :class => 'multiselect'
            %td
              = text_field_tag 'filter[search]', "#{params[:filter][:search] if params[:filter]}"
            %td
              = hidden_field_tag 'filter[kabupaten_id]', "#{params[:filter][:kabupaten_id] if params[:filter]}"
              = autocomplete_field_tag :kabupaten_name, '', autocomplete_kabupaten_name_kabupatens_path, id_element: "#filter_kabupaten_id", value: "#{@kabupaten.try(:name)}"
            %td{style: 'vertical-align: top'}
              %input{:type => 'submit', :value => 'Filter', class: 'btn'}

- if @projects.present?

  %p= page_entries_info @projects

  %table.table.table-striped
    %tr
      %th{style: 'width:20%'}= t('kabupaten.title').titleize
      %th= t('kabupaten.description').titleize
      %th{style: 'width:15%'}= t('kabupaten.location').titleize
      %th{style: 'width:15%'}= t('kabupaten.sector').titleize

    - @projects.each do |project|
      %tr
        %td
          = link_to project.name, project
        %td
          = strip_tags(project.description).try(:truncate, 300)
        %td
          = raw(project.kabupatens.map{|k| link_to k.category_name, kabupaten_path(k.id)}.join(', '))
        %td= raw(project.sectors(order: :name).map{|s| link_to s.name, projects_path(filter: {:sector_id => [s.id]})}.join(', '))

  = will_paginate @projects

-else
  %p There are no projects to list
%br

= link_to 'Submit a Project', new_project_path, :class => 'btn btn-primary'

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path, :class => 'btn'

app/views/projects/show.html.haml
- @page_title = @project.name
- @body_class = "projects"

/ %p#notice= notice

%p.user
  Created by
  = link_to @project.user.name, user_path(@project.user)

#project_description
  = raw(@project.description)
- if Translate.for_translation?(@project, 'description')
  .alert{style: 'margin-top: 10px'}
    = t('kabupaten.translate_alert')
    %br
    - translate_button('project_description')


%table.simple_table{style: 'margin-top: 20px'}
  %tr
    %th== #{t('kabupaten.location').titleize}:
    %td
      - @project.kabupatens.each do |kabupaten|
        %strong= "#{kabupaten.province.name}: "
        = link_to kabupaten.category_name, kabupaten
        %br
  %tr
    %th== #{t('kabupaten.sector').titleize}:
    %td
      - @project.sectors.sort_by(&:name).each do |sector|
        = sector.name
        %br

= render :partial => '/links', :locals => {:linkable => @project}

- if can? :update, @project
  = link_to 'Edit', edit_project_path(@project), :class => 'btn'
= link_to 'Back', projects_path, :class => 'btn'