config/routes.rb
Kabupatenku::Application.routes.draw do

  mount Tolk::Engine => '/tolk', :as => 'tolk'

  devise_for :users

  resources :registrations, :only => [:show]

  resources :users, :only => [:index, :show, :edit, :update]
  resources :provinces

  resources :kabupatens do
    get :autocomplete_kabupaten_name, :on => :collection
    resources :links,    :only => [:create, :update, :destroy]
  end

  resources :projects do
    resources :links,    :only => [:create, :update, :destroy]
  end
  resources :contacts
  resources :sectors

  resource :dashboard, :controller => "dashboard", :only => [:show]
  resource :corporate, :controller => "corporate", :only => [:show]
  resource :translate, :controller => "translate", :only => [] do
    member do
      post 'translate'
    end
  end

  resource :admins

  resources :snippets

  authenticated :user do
    root :to => 'dashboard#show'
  end

  root :to => "dashboard#show"

end

app/views/layouts/admins.html.haml
!!!
%html{ 'lang' => locale }
  %head
    %meta{ 'http-equiv' => 'Content-Type', :content => 'text/html; charset=utf-8' }
    %meta{ name: "google-translate-customization", content: "4d9c898eb7b9dc59-f3255ce5be3f524d-ge71e457f8ee0c1f1-11"}
    %title= @page_title || 'Kabupaten Administration'
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = javascript_include_tag "jquery.multiselect." + I18n.locale.to_s, "jquery.multiselect.filter." + I18n.locale.to_s

    = yield :javascript_includes
    = csrf_meta_tag
    = yield :stylesheet_includes

  %body{:class => "#{@body_class}"}
    .container.bg
      #menubar.navbar
        #site-actions.navbar-inner
          %a.brand{ href: root_path } kabupaten.org
          %ul.nav.pull-right
            - if locale == :id
              %li= link_to image_tag('en-flg.gif', title: 'English'), locale_uri('www')
            - else
              %li= link_to image_tag('id-flg.gif', title: 'Bhs Indonesia'), locale_uri('id')
            %li{ class: "#{'active' if current_page?(admins_path)}" }= link_to t('kabupaten.home'), admins_path
            - if can? :manage, User
              %li{ class: "#{'active' if controller.controller_name == 'users'}" }= link_to 'Users', users_path
            %li{ class: "#{'active' if controller.controller_name == 'snippets'}" }= link_to 'Snippets', snippets_path
            - if current_user
              %li.dropdown
                %a.dropdown-toggle(data-toggle="dropdown" href="#")
                  = current_user.name
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to t('devise.sessions.sign_out'), destroy_user_session_path, :method => 'delete'
            - else
              %li= link_to t('devise.sessions.sign_in'), new_user_session_path

      %header
        #messages
          - display_flash
        %h2
          = @page_title
      - if content_for? :sidebar
        .row
          .span12.bg
            .row
              .span8
                .main
                  = yield
              .span4
                .sidebar
                  = yield :sidebar
            .bottom-content
              = yield :bottom
      - else
        .row
          .span12.bg
            .main
              = yield

      .bottom-space
        %p &nbsp;

      %footer
        .container
          %p
            %span.footer-link= link_to t('kabupaten.contact_us'), corporate_path(page: "contact")
          %p
            %span.copyright= raw('&copy;') + " #{Time.now.year} kabupaten.org"
            %span.social_networks.pull-right
              %a(href="https://twitter.com/kabupaten_org" class="twitter-follow-button" data-show-count="false") Follow @kabupaten_org
              :plain
                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/layouts/application.html.haml
!!!
%html{ 'lang' => locale }
  %head
    %meta{ 'http-equiv' => 'Content-Type', :content => 'text/html; charset=utf-8' }
    %meta{ name: "google-translate-customization", content: "4d9c898eb7b9dc59-f3255ce5be3f524d-ge71e457f8ee0c1f1-11"}
    %title= @page_title || 'Kabupaten'
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = javascript_include_tag "jquery.multiselect." + I18n.locale.to_s, "jquery.multiselect.filter." + I18n.locale.to_s

    = yield :javascript_includes
    = csrf_meta_tag
    = yield :stylesheet_includes

  %body{:class => "#{@body_class}"}
    .container.bg
      #menubar.navbar
        #site-actions.navbar-inner
          %a.brand{ href: root_path } kabupaten.org
          %ul.nav.pull-right
            - if locale == :id
              %li= link_to image_tag('en-flg.gif', title: 'English'), locale_uri('www')
            - else
              %li= link_to image_tag('id-flg.gif', title: 'Bhs Indonesia'), locale_uri('id')
            %li{ class: "#{'active' if current_page?(root_path)}" }= link_to t('kabupaten.home'), root_path
            %li.dropdown{ class: "#{'active' if controller.controller_name == 'kabupatens'}" }
              %a.dropdown-toggle(data-toggle="dropdown" href="#")
                Kabupaten
                %b.caret
              %ul.dropdown-menu
                = link_to 'All', kabupatens_path
                - Province.by_name.each do |province|
                  = link_to province.name, kabupatens_path(province: province.id)
            %li{ class: "#{'active' if controller.controller_name == 'projects'}" }= link_to t('kabupaten.projects').titleize, projects_path
            %li{ class: "#{'active' if current_page?(corporate_path(page: "about"))}" }= link_to t('kabupaten.about_us'), corporate_path(page: "about")
            %li{ class: "#{'active' if current_page?(corporate_path(page: "contact"))}"}= link_to t('kabupaten.contact_us'), corporate_path(page: "contact")
            - if current_user
              %li.dropdown
                %a.dropdown-toggle(data-toggle="dropdown" href="#")
                  = current_user.name
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to t('devise.sessions.sign_out'), destroy_user_session_path, :method => 'delete'
                  %li= link_to t('my_details'), registration_path(current_user)
            - else
              %li= link_to t('devise.sessions.sign_in'), new_user_session_path

      %header
        #messages
          - display_flash
        %h2
          = @page_title
      - if content_for? :sidebar
        .row
          .span12.bg
            .row
              .span8
                .main
                  = yield
              .span4
                .sidebar
                  = yield :sidebar
            .bottom-content
              = yield :bottom
      - else
        .row
          .span12.bg
            .main
              = yield

      .bottom-space
        %p &nbsp;

      %footer
        .container
          %p
            %span.footer-link= link_to t('kabupaten.contact_us'), corporate_path(page: "contact")
          %p
            %span.copyright= raw('&copy;') + " #{Time.now.year} kabupaten.org"
            %span.social_networks.pull-right
              %a(href="https://twitter.com/kabupaten_org" class="twitter-follow-button" data-show-count="false") Follow @kabupaten_org
              :plain
                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>